# Generated by Django 2.2 on 2019-10-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191001_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='beverages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='', verbose_name='images')),
                ('body', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('No_of_items', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fooditems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='', verbose_name='images')),
                ('body', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('No_of_items', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='grocery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='', verbose_name='images')),
                ('body', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('No_of_items', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='homeutilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='', verbose_name='images')),
                ('body', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('No_of_items', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='prod',
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
