# Generated by Django 2.2 on 2019-10-03 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191004_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='exp_date',
        ),
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
