# Generated by Django 2.2 on 2019-10-03 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191004_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exp_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
