# Generated by Django 2.2 on 2019-10-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_exp_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='exp_date',
        ),
    ]
