# Generated by Django 2.2 on 2019-10-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20191004_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='a',
        ),
    ]
