# Generated by Django 2.2 on 2019-10-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='a',
            field=models.IntegerField(default=1),
        ),
    ]
