# Generated by Django 2.2 on 2019-10-03 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='a',
        ),
        migrations.AddField(
            model_name='product',
            name='exp_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
